# Generated by Django 4.2.5 on 2023-10-03 16:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название модели')),
                ('category', models.CharField(max_length=255, verbose_name='Категория модели')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание модели')),
                ('ml_model', models.FileField(upload_to='ml_models/', verbose_name='Файл модели МО')),
                ('inputs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=None)),
            ],
        ),
    ]
