# Generated by Django 4.2.5 on 2023-10-05 13:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=80), default='{cat1,cat2}', size=None),
            preserve_default=False,
        ),
    ]
