# Generated by Django 4.2.5 on 2023-10-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0002_remove_mlmodel_category_mlmodel_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=80, verbose_name='Тэг модели')),
            ],
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='categories',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Tag', to='ml_models.modeltag', verbose_name='Тэги модели'),
        ),
    ]
