# Generated by Django 4.2.5 on 2023-10-06 15:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0003_modeltag_remove_mlmodel_categories_mlmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='inputs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_index=True, max_length=25), size=None),
        ),
    ]
