# Generated by Django 4.2.5 on 2023-10-18 09:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0004_alter_mlmodel_inputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='inputs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, db_index=True, max_length=25, verbose_name='Имена принимаемых входных данных'), size=None),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='ml_model',
            field=models.FileField(blank=True, upload_to='ml_models/', verbose_name='Файл модели МО'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='models_with_tag', to='ml_models.modeltag', verbose_name='Тэги модели'),
        ),
        migrations.AlterField(
            model_name='modeltag',
            name='tag',
            field=models.CharField(max_length=80, unique=True, verbose_name='Тэг модели'),
        ),
    ]
